### ISSUE TITLE
Error Displayed while customizing project 

### ISSUE THREAD

**Issue by caiyuanji** [btechpt/yuyu#1]
Error Displayed while customizing project . As follows: Error: 
Unable to get invoice [Details](http://10.12.50.13/horizon/admin/projects_invoice/?project_id=79ca0b282c92476e900180b0ae73f095&project_name=enflame#message_details)
Expecting value: line 1 column 1 (char 0)

Have you tested in custom projects?

**Comment by irfanpule** [comment]
Hi @caiyuanji thank for your report.

I can't get detail error from your link detail. Can you give screenshot or accessable link?

**Comment by caiyuanji** [comment]
I created a project, logged in as a normal user, and created a virtual machine instance in the project, but could not view the information under the Billing option of the project。

I can view information about the project as Admin.  Why? At the very least, each user can see the billing information for his or her own project.  Did I get that wrong?

**Comment by irfanpule** [comment]
I see. We have found your problem. We will fix it in the next release.
For the alternative solution, you can login as admin and then go to menu -> Billing -> Billing Setting -> re-enable billing (click button `Disable Billing` after then `Enable Billing`).

After then you can test login as a normal user. I hope this helping you.

**Comment by caiyuanji** [comment]
File "/var/yuyu/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked

Does yuyu support mysql ?

**Comment by caiyuanji** [comment]
Pricing is supported only for integers, not floating points，
the price of some items cannot be set to 0, such as the price of routes

**Comment by irfanpule** [comment]
> File "/var/yuyu/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute return Database.Cursor.execute(self, query, params) django.db.utils.OperationalError: database is locked
> 
> Does yuyu support mysql ?

basically you can change db to mysql or postgresql. This project create use Django, so you can change db configuration to settings.py. In this projects you just override in local_settings.py

**Comment by irfanpule** [comment]
> Pricing is supported only for integers, not floating points，
> the price of some items cannot be set to 0, such as the price of routes

Thanks for your report. For this we may be missed because it focuses only on IDR. We will fix it

**Comment by irfanpule** [comment]
Hi @caiyuanji 
We have released a new version for this issue. Please see here
https://github.com/btechpt/yuyu/releases/tag/v1.0.1
