### ISSUE TITLE
Pricing is supported only for integers, not floating points，

### ISSUE THREAD

**Issue by irfanpule** [btechpt/yuyu#3]
Pricing is supported only for integers, not floating points，
the price of some items cannot be set to 0, such as the price of routes

_Originally posted by @caiyuanji in https://github.com/btechpt/yuyu/issues/1#issuecomment-1288835165_

**Comment by setyongr** [comment]
Thanks for reporting the issue.

Now, you can use decimal/floating point on price configuration. Please update your Yuyu to version `v1.0.1`.

Thank you.
